name: 'Run OpenMCx'
description: 'An action script that will perform simulations using the 
              open-source Co-Simulation Middleware eclipse OpenMCx'
inputs:
  ssd: 
    description: 'Path to the System Structure Definition (SSD) file that define
                  the simulation that shall be executed. For running more than
                  one single simulation, separate the paths for each SSD file
                  using a white space.
                  Examples: 
                  Single file: "./path/to/system.ssd"
                  Multiple files: "./path/to/system1.ssd ./path/to/system2.ssd"'
    required: true
runs:
  using: "composite"
  steps:
    - name: Install openmcx prerequisites
      run: |
        sudo apt update
        sudo apt install -y cmake git
        sudo apt install -y build-essential
        sudo apt install -y python-is-python3
        sudo apt install -y libxml2-dev zlib1g-dev
    - name: Checkout openmcx
      uses: actions/checkout@v4
      with: 
        repository: eclipse/openmcx
        path: 'openmcx'
    - name: build openmcx
      working-directory: openmcx
      run: ./build.sh
    - name: run simulation
      shell: bash
      run: |
        ssdFiles=(${{ inputs.ssd }})
        nSimulations=${#ssdFiles[@]}
        for ssdPath in ${ssdFiles[@]}; do ./openmcx/install/openmcx $ssdPath -v; done